export enum TYPE_PROYECT {
  EXISTING = "EXISTING",
  NEW = "NEW"
}

export enum OPTIONS {
  GENERATE_ROUTE = "GENERATE_ROUTE",
  GENERATE_CONTROLLER = "GENERATE_CONTROLLER",
  GENERATE_MODULE = "GENERATE_MODULE",
  GENERATE_VALIDATION_FILE = "GENERATE_VALIDATION_FILE"
}